---
- name: check go version
  shell: "{{ go_path }} version"
  register: current_go_version
  ignore_errors: True

- name: install go
  action: command {{ item }}
  with_items:
    - rm -rf {{ go_root_path }}/go
    - wget https://storage.googleapis.com/golang/go{{ go_version }}.{{ go_os }}-{{ go_arch }}.tar.gz
    - tar -C {{ go_root_path }} -xzf go{{ go_version }}.{{ go_os }}-{{ go_arch }}.tar.gz
    - rm go{{ go_version }}.{{ go_os }}-{{ go_arch }}.tar.gz
  when: "'{{ go_version }}' not in '{{ current_go_version.stdout }}'"

- name: append path
  lineinfile: dest=/etc/profile line="{{ item }}"
  with_items:
    - export PATH=$PATH:{{ go_path }}